'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be...
...By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

#Code than create a fibonacci sequence
final_count = 4_000_000
first_number = 0
second_number = 1
final_sum = 0

new_number = first_number+second_number
while new_number <= final_count:
    
    first_number = second_number
    second_number =  new_number
    
    if new_number%2 == 0:
        final_sum += new_number
        
    new_number = first_number+second_number

print(final_sum)
